

export const BUILDING_CREATION_REQUEST = 'BUILDING_CREATION_REQUEST';
export const BUILDING_CREATION_SUCCESS = 'BUILDING_CREATION_SUCCESS';
export const BUILDING_CREATION_FAIL = 'BUILDING_CREATION_FAIL';
export const BUILDING_FETCHING_FAIL = 'BUILDING_FETCHING_FAIL';


export const BUILDING_FETCHING_REQUEST = 'BUILDING_FETCHING_REQUEST';

export const BUILDING_FETCHING_SUCCESS = 'BUILDING_FETCHING_SUCCESS';

export const BUILDING_EDIT_FAIL = 'BUILDING_EDIT_FAIL';
export const BUILDING_EDIT_SUCCESS = 'BUILDING_EDIT_SUCCESS';
export const BUILDING_EDIT_REQUEST = 'BUILDING_EDIT_REQUEST';
export const BUILDING_CLEAN = 'BUILDING_CLEAN';



export const USER_FETCHING_REQUEST = 'USER_FETCHING_REQUEST';
export const USER_FETCHING_SUCCESS = 'USER_FETCHING_SUCCESS';
export const USER_FETCHING_FAIL = 'USER_FETCHING_FAIL';
export const USER_CREATION_SUCCESS = 'USER_CREATION_SUCCESS';
export const USER_CREATION_REQUEST = 'USER_CREATION_REQUEST';
export const USER_CREATION_FAIL = 'USER_CREATION_FAIL';



export const BUILDING_DELITING_SUCCESS = 'BUILDING_DELITING_SUCCESS';
export const BUILDING_DELITING_FAIL = 'BUILDING_DELITING_FAIL';
export const BUILDING_DELITING_REQUEST = 'BUILDING_DELITING_REQUEST';